// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/terax-cms/Console.tsx": () => import("../components/mockups/terax-cms/Console.tsx")
};
